Update ARM.CMSIS.pdsc to add Cortex-M52 Dcore
ARM-software/CMSIS_6 pull request #137
Opened 2024-02-22 08:28 UTC by AlbertHuang-CPU

2024-02-22 09:05 UTC, JonatanAntoni requested changes

2024-02-22 09:05 UTC, JonatanAntoni commented on ARM.CMSIS.pdsc
> +      <accept Dcore="Cortex-M52"/>
Schema version needs to be updated in order to allow new value for `Dcore`.

2024-02-22 09:07 UTC, JonatanAntoni commented on ARM.CMSIS.pdsc
> +      <accept Dcore="Cortex-M52"/>
I created schema version tag `v1.7.31`

2024-02-23 02:49 UTC, AlbertHuang-CPU commented on ARM.CMSIS.pdsc
> +      <accept Dcore="Cortex-M52"/>
Updated schema version to v1.7.31

2024-02-23 11:01 UTC, JonatanAntoni approved these changes

2024-02-23 11:01 UTC, merged