add bpu struct for core_starmc1.h
ARM-software/CMSIS_6 pull request #174
Opened 2024-06-13 07:08 UTC by GuangMing34

2024-06-13 07:11 UTC, JonatanAntoni commented
@AlbertHuang-CPU, may I ask you to review this contribution, please?

2024-06-25 08:10 UTC, AlbertHuang-CPU requested changes

2024-06-25 08:10 UTC, AlbertHuang-CPU commented on CMSIS/Core/Include/core_starmc1.h
> +#define BPU_COMP_BPADDR_Msk            (0xFFFFFFFEUL << BPU_COMP_BPADDR_Pos)   /*!< BPU COMP: BPADDR Mask */
The "0xFFFFFFFEUL" shall be "0x7FFFFFFF".

2024-06-25 08:22 UTC, JonatanAntoni commented on CMSIS/Core/Include/core_starmc1.h
> +#define BPU_COMP_BPADDR_Msk            (0xFFFFFFFEUL << BPU_COMP_BPADDR_Pos)   /*!< BPU COMP: BPADDR Mask */
```suggestion
#define BPU_COMP_BPADDR_Msk            (0x7FFFFFFFUL << BPU_COMP_BPADDR_Pos)   /*!< BPU COMP: BPADDR Mask */
```

2024-07-08 08:11 UTC, JonatanAntoni commented
@GuangMing34, are you still working on this contribution? Could you look into the review comments added by @AlbertHuang-CPU, please?

2024-07-09 07:58 UTC, GuangMing34 commented
Hi @JonatanAntoni , I saw you already force pushed a new commit to fix it, I'm not familiar with pull request, could you tell me what I should do next? Thanks~

2024-07-09 13:24 UTC, JonatanAntoni commented
@GuangMing34, just double check what I pushed. I just accepted the changes requested by @AlbertHuang-CPU. If this is as expected for you I am fine with merging this PR.

2024-07-10 06:11 UTC, GuangMing34 commented
@JonatanAntoni, already checked, it's ok. Thanks~

2024-07-10 14:41 UTC, JonatanAntoni approved these changes

2024-07-10 14:41 UTC, merged