* Retire the Core_A folder and use a single Core folder for all processor core headers.
ARM-software/CMSIS_6 pull request #38
Opened 2023-08-07 21:46 UTC by Masmiseim36

* Separate folders for different architecture profiles (A-profile, R-profile and M-profile)
* Top-level compiler headers will exist in the Core folder (no separate Compiler folder is needed). ** The cmsis_compiler.h header will continue to figure out which compiler toolchain is being used. ** Compiler headers specific to each architecture profiles can reside within the new architecture profile folders. ** The second-level files like cmsis_gcc.h are named cmsis_gcc_a.h, cmsis_gcc_r.h and cmsis_gcc_m.h to avoid having multiple files with the same name

2023-08-08 07:43 UTC, JonatanAntoni requested changes
The `core_armv8xxx.h` are effectively core header files (even if not implementing a specific core but only architecture generic features) and need to stay on top level. As they do not relate to any specific core, we might decide to remove them from CMSIS 6 (@GuentherMartin, what do you think?).

2023-08-08 09:08 UTC, GuentherMartin commented
In my opinion we should delete the core_armv8xxx.h core header files.
These are the only header files representing an architecture and not a dedicated core. The files were added because no specific ARM v8-M device was available when Arm v-M support was added.

2023-08-08 10:28 UTC, GuentherMartin commented on CMSIS/Core/Include/a-profile/cmsis_armcc_a.h
In my opinion this file is obsolete.
Arm Compiler V5 (ARMCC) is no longer used

2023-08-08 10:32 UTC, GuentherMartin commented on CMSIS/Core/Include/m-profile/core_armv81mml.h
In my opinion this file should be deleted.

2023-08-08 10:32 UTC, GuentherMartin commented on CMSIS/Core/Include/m-profile/core_armv8mbl.h
In my opinion this file should be deleted.

2023-08-08 10:32 UTC, GuentherMartin commented on CMSIS/Core/Include/m-profile/core_armv8mml.h
In my opinion this file should be deleted.

2023-08-08 10:33 UTC, GuentherMartin submitted a review, later dismissed

2023-08-08 18:42 UTC, Masmiseim36 commented
Hello @JonatanAntoni and @GuentherMartin 

thank you for the feedback. I have updated the Pull-Request according to your input.

2023-08-09 09:31 UTC, Masmiseim36 commented
@JonatanAntoni  Is there anything I can do regarding the validation errors?

2023-08-09 09:33 UTC, JonatanAntoni commented
> @JonatanAntoni Is there anything I can do regarding the validation errors?

No, unfortunately, to run the tests we need the license key which I stored in a repository secret. For security reasons a PR from a fork doesn't get access to these. Hence, we cannot execute the tests.

2023-08-09 10:31 UTC, merged